import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ApiService } from './api.service';

export type QuizVisibility = 'private' | 'unlisted' | 'public';
export type QuizStatus = 'draft' | 'published';
export type QuizSort = 'newest' | 'popular' | 'alpha';
/** AI transformation lineage: a quiz created by AI from a parent quiz. */
export type QuizTransformationType = 'remix' | 'translate';
/** BCP-47 language tag (e.g. `en`, `es`, `zh-CN`). */
export type QuizLanguage = string;

export interface QuizSummary {
  id: number;
  title: string;
  description: string | null;
  share_code: string | null;
  created_at: string;
  questionCount: number;
  visibility?: QuizVisibility;
  status?: QuizStatus;
  playCount?: number;
  // AI transformation lineage — set when this quiz was generated by AI
  // (remix or translate). Undefined for human-authored originals.
  parentQuizId?: number;
  transformationType?: QuizTransformationType;
  language?: QuizLanguage;
}

/**
 * Canonical question type union. The backend stores and returns one of these
 * strings in the `questions.type` column. The frontend uses the same vocabulary
 * in save payloads, websocket events (as a plain string), and UI builders.
 */
export type QuestionType =
  | 'multiple-choice'
  | 'true-false'
  | 'ordering'
  | 'matching'
  | 'fill-in-blank';

/**
 * A single option row. The shape is intentionally permissive: most fields are
 * optional and only relevant for a subset of question types.
 *
 * - `matchId`     — matching only: id of the right-side item this left item
 *                   pairs with. Stripped from public payloads.
 * - `answer`      — fill-in-blank only: the canonical accepted text. Stripped
 *                   from public payloads (replaced with `text: '___'`).
 * - `caseSensitive` — fill-in-blank only: per-answer case sensitivity flag.
 *                   Stripped from public payloads.
 */
export interface QuizOptionDto {
  id: string;
  text: string;
  matchId?: string;
  answer?: string;
  caseSensitive?: boolean;
}

/**
 * Shape of the `options` field for the public/player-facing question payload
 * (correct answers stripped). For matching, the left items live in `options`
 * and the shuffled right items live in `rightOptions` on the question itself.
 */
export type QuizOptions = QuizOptionDto[];

/**
 * Player-facing question payload. `correct_answer` is `null` for the public
 * payload — the server strips it. `rightOptions` is matching-only and holds
 * the right column items with `matchId` removed.
 */
export interface QuizQuestionDto {
  id: number;
  quiz_id: number;
  text: string;
  type: QuestionType;
  options: QuizOptionDto[];
  rightOptions?: QuizOptionDto[];
  correct_answer: string | null;
  time_limit: number | null;
  points: number;
  order_index: number;
}

export interface QuizDetailDto {
  id: number;
  title: string;
  description: string | null;
  share_code: string | null;
  created_at: string;
  questions: QuizQuestionDto[];
  visibility?: QuizVisibility;
  status?: QuizStatus;
  playCount?: number;
}

export interface QuizSaveResponse {
  quiz: {
    id: number;
    title: string;
    description: string | null;
    creator_id: string;
    share_code: string | null;
    created_at: string;
    visibility?: QuizVisibility;
    status?: QuizStatus;
    playCount?: number;
  };
  shareCode: string;
}

/**
 * Save payload for a single question.
 *
 * The `options` field is a flat `QuizOptionDto[]` for `multiple-choice`,
 * `true-false`, `ordering`, and `fill-in-blank` (the `correct_answer`
 * semantics vary by type — see the type-specific notes below). For
 * `matching`, `options` is the richer `{ left, right }` shape.
 *
 * - `multiple-choice` — `correct_answer` is the chosen option id.
 * - `true-false` — `correct_answer` is the literal `'true'` or `'false'`.
 * - `ordering` — `correct_answer` is JSON of the correct order id list.
 * - `matching` — `correct_answer` is JSON of the `{ leftId: rightId }` map.
 * - `fill-in-blank` — `correct_answer` is the canonical (first) accepted answer.
 */
export type QuizQuestionPayload =
  | {
      text: string;
      type: 'multiple-choice' | 'true-false' | 'ordering' | 'fill-in-blank';
      options: QuizOptionDto[];
      correct_answer: string;
      time_limit?: number;
      points?: number;
    }
  | {
      text: string;
      type: 'matching';
      options: { left: QuizOptionDto[]; right: QuizOptionDto[] };
      correct_answer: string;
      time_limit?: number;
      points?: number;
    };

export interface QuizSavePayload {
  title: string;
  description?: string;
  questions: QuizQuestionPayload[];
  visibility?: QuizVisibility;
  status?: QuizStatus;
}

// ---------------------------------------------------------------------------
// AI Quiz Generation
// ---------------------------------------------------------------------------

export interface AiGenerateRequest {
  title: string;
  notes: string;
  instructions?: string;
}

export interface AiGeneratedQuestion {
  text: string;
  type: QuestionType;
  options: unknown;
  correct_answer: string;
  time_limit?: number;
  points?: number;
}

export interface AiGenerateResponse {
  data: {
    questions: AiGeneratedQuestion[];
  };
  meta: {
    count: number;
  };
}

// ---------------------------------------------------------------------------
// AI Quiz Remix (creates a new owned quiz from an existing one)
// ---------------------------------------------------------------------------

export interface AiRemixRequest {
  instructions?: string;
}

export interface AiRemixResponse {
  quiz: QuizSummary & {
    parentQuizId: number;
    transformationType: 'remix';
    language: QuizLanguage;
  };
  shareCode: string;
  transformationType: 'remix';
  /** True when an existing remix was reused (currently always false — remix is always fresh). */
  reused: boolean;
}

// ---------------------------------------------------------------------------
// AI Quiz Translate (creates a new owned quiz in a target language)
// ---------------------------------------------------------------------------

export interface AiTranslateRequest {
  targetLanguage: string;
}

export interface AiTranslateResponse {
  quiz: QuizSummary & {
    parentQuizId: number;
    transformationType: 'translate';
    language: QuizLanguage;
  };
  shareCode: string;
  transformationType: 'translate';
  targetLanguage: string;
  /** True when an existing translation was reused (dedup hit). */
  reused: boolean;
}

// ---------------------------------------------------------------------------
// Discovery (public discover feed)
// ---------------------------------------------------------------------------

export interface DiscoverQuizzesQuery {
  query?: string;
  sort?: QuizSort;
  limit?: number;
  offset?: number;
}

export interface DiscoverQuizCreator {
  user_id: string;
  username: string;
  display_name: string;
}

export interface DiscoverQuizSummary {
  id: number;
  title: string;
  description: string | null;
  question_count: number;
  creator: DiscoverQuizCreator | null;
  play_count: number;
  created_at: string;
  share_code: string;
}

export interface DiscoverQuizzesResponse {
  items: DiscoverQuizSummary[];
  total: number;
  limit: number;
  offset: number;
}

@Injectable({ providedIn: 'root' })
export class QuizApiService {
  private readonly apiService = inject(ApiService);

  getMyQuizzes(): Observable<QuizSummary[]> {
    return this.apiService.get<QuizSummary[]>('/api/quizzes');
  }

  getQuizById(quizId: number): Observable<QuizDetailDto> {
    return this.apiService.get<QuizDetailDto>(`/api/quizzes/${quizId}`);
  }

  createQuiz(payload: QuizSavePayload): Observable<QuizSaveResponse> {
    return this.apiService.post<QuizSaveResponse>('/api/quizzes', payload);
  }

  updateQuiz(quizId: number, payload: QuizSavePayload): Observable<QuizDetailDto> {
    return this.apiService.patch<QuizDetailDto>(`/api/quizzes/${quizId}`, payload);
  }

  deleteQuiz(quizId: number): Observable<void> {
    return this.apiService.delete<void>(`/api/quizzes/${quizId}`);
  }

  aiGenerateQuiz(payload: AiGenerateRequest): Observable<AiGenerateResponse> {
    return this.apiService.post<AiGenerateResponse>('/api/quizzes/ai-generate', payload);
  }

  /**
   * Remixes one of the user's own quizzes via AI, creating a NEW owned
   * quiz with `transformationType: 'remix'`. The source quiz is not modified.
   */
  aiRemixQuiz(sourceQuizId: number, payload: AiRemixRequest): Observable<AiRemixResponse> {
    return this.apiService.post<AiRemixResponse>(
      `/api/quizzes/${sourceQuizId}/ai-remix`,
      payload
    );
  }

  /**
   * Translates one of the user's own quizzes to a target language via AI,
   * creating a NEW owned quiz with `transformationType: 'translate'`. If the
   * user already has a translation of this source quiz to the same target
   * language, the existing quiz is returned (no duplicate).
   */
  aiTranslateQuiz(
    sourceQuizId: number,
    payload: AiTranslateRequest
  ): Observable<AiTranslateResponse> {
    return this.apiService.post<AiTranslateResponse>(
      `/api/quizzes/${sourceQuizId}/ai-translate`,
      payload
    );
  }

  searchPublicQuizzes(
    query = '',
    sort: QuizSort = 'newest',
    limit = 24,
    offset = 0
  ): Observable<DiscoverQuizzesResponse> {
    const params = new URLSearchParams();
    if (query.trim()) {
      params.set('query', query.trim());
    }
    if (sort) {
      params.set('sort', sort);
    }
    if (limit) {
      params.set('limit', String(limit));
    }
    if (offset) {
      params.set('offset', String(offset));
    }
    const qs = params.toString();
    return this.apiService.get<DiscoverQuizzesResponse>(
      `/api/quizzes/discover${qs ? `?${qs}` : ''}`
    );
  }
}
